name: 'Release'
on:
  create:
    tags:
      - v*
  push:
    branches:    
      - master
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: run
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: go test ./...
  build:
    name: 'Build'
    if: startsWith(github.ref, 'refs/tags/v') # Only run builds on versioned tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "darwin"]
        goarch: ["386", "amd64"]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Build
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: go build -o edward .
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - run: zip edward_${{ steps.tagName.outputs.tag }}_${{ matrix.goos }}_${{ matrix.goarch}}.zip edward
      - name: Add build asset
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: edward_${{ steps.tagName.outputs.tag }}_${{ matrix.goos }}_${{ matrix.goarch}}.zip
  release:
    name: 'Release'
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.tagName.outputs.tag }}
          release_name: Release ${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: false
      - run: echo ${{ steps.create_release.outputs.upload_url }} > upload_url.txt
      - name: Save upload URL
        uses: actions/upload-artifact@v1
        with:
          name: upload_url
          path: upload_url.txt
  upload:
    name: 'Upload'
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "darwin"]
        goarch: ["386", "amd64"]
    steps:
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Get upload URL
        uses: actions/download-artifact@v1
        with:
          name: upload_url
      - name: Save upload_url
        id: upload
        run: echo "::set-output name=url::`cat upload_url/upload_url.txt`"
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload.outputs.url }}
          asset_path: build/edward_${{ steps.tagName.outputs.tag }}_${{ matrix.goos }}_${{ matrix.goarch}}.zip
          asset_name: edward_${{ steps.tagName.outputs.tag }}_${{ matrix.goos }}_${{ matrix.goarch}}.zip
          asset_content_type: application/zip